# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActApp' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'

  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ActApp

  

  platform :ios, '9.0'
  target 'ActAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ActApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ActApp-tvOS

  target 'ActApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
