export const EVENT_SHARE_STARTED = "SHARE_STARTED";
export const EVENT_STEP_COMPLETED = "STEP_COMPLETED";
export const EVENT_SHARE_COMPLETED = "SHARE_COMPLETED";
export const CONTACT_ADDED = "CONTACT_ADDED";

export const PARAM_STEP_KEY = "STEP_KEY";
export const PARAM_ACCEPTED_CHRIST = "ACCEPTED_CHRIST";

export const PAGE_HOME = 'HOME'